//UI interfacing structs
/*struct startArgs
{
	const char* header;
	vector<string> scripts;
	int concurrency;
};*/

/*
interface main {
	[in]
	void start({string header, array<string> scripts, int concurrency});
	[out]
	void run({int argc, array<string> argv});
	
}
*/

/*
 * <app>
 * 		<iface name="main">
 * 			<inslot name="start" signature="void(A<O>{string header, A<string> scripts, int32 concurrency})" />
 * 		</iface>
 * </app>
 * 
 * 
 * */
