#!/bin/bash
cat <<EOF
server.modules = (
	"mod_access",
	"mod_alias",
	"mod_ssi",
	"mod_compress",
	"mod_redirect",
	"mod_rewrite",
	"mod_fastcgi"
)
fastcgi.server = (
	"/fcgi_test" =>
	(( "socket" => "$(pwd)/fcgi_test.sock", 
		  "bin-path" => "$(pwd)/fcgi_test" 
	)),
	".C" => 
	((
		"socket" => "$(pwd)/fcgi_test.sock", 
		  "bin-path" => "$(pwd)/fcgi_test" 
	))
)
mimetype.assign   = ( ".png"  => "image/png",
                      ".jpg"  => "image/jpeg",
                      ".jpeg" => "image/jpeg",
                      ".htm" => "text/html",
                      ".mp3" => "audio/mp3",
                      ".oga" => "audio/ogg",
                      ".html" => "text/html",
			".css" => "text/css",
                      ".txt"  => "text/plain" )
ssi.extension = ( ".shtml" , ".htm", ".html")
server.port = 12580
server.document-root        = "$(pwd)"
server.pid-file             = "$(pwd)/lighttpd.pid"

index-file.names            = ( "index.php", "index.html",
                                "index.htm", "default.htm",
                               " index.lighttpd.html" )

url.access-deny             = ( "~", ".inc" )

dir-listing.encoding        = "utf-8"
server.dir-listing          = "enable"

compress.filetype           = ( "application/x-javascript", "text/css", "text/html", "text/plain" )
EOF


