#!/bin/bash
# usage: run_application /ABSOLUTE/PATH/TO/APPLICATION

num_cpus=`grep vendor_id /proc/cpuinfo | wc -l`
./cppsp_standalone -f -l 0.0.0.0:16969 -c -fPIC -c -I"$(pwd)"/../include -c -L"$(pwd)"/../lib -c -pthread -c -Ofast -c -march=native -c -lcpoll -c -lcppsp -t "$num_cpus" -r "$@"


