#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#
#  ifsrv.py - Interface service - network interface management daemon
#  
#  Copyright 2012  <xaxaxa@xaxaxa-mac>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#***config file format***
#*global options*
#	option (option name) (value)
#*config definition*
#	config (name):
#		option (name) (value)
#	...
#	end
#*interface definition*
#	iface (name):
#		option (name) (value)
#	...
#	end
#	
#***global options***
#	nowait: do not wait for the interface to be configured; (yes|no)
#
#***config options***
#	these are self explanatory: type(static|dhcp), address, netmask, gateway
#
#***interface options***
#	nowait
#	config: configurations for this interface; separated by space; they're tried in the order specified

import sys;
def readconfig(f):
	obj={"options":{},"configs":[],"interfaces":[]};
	array_opts=["configs"];
	cur_scope=(None,None);
	while True:
		tmp=f.readline();
		if tmp==None or len(tmp)<=0: return obj;
		a=tmp.split();
		if len(a)<1: continue;
		cmd=a[0];
		if cmd=="option":
			optval=None;
			if a[1] in array_opts:
				optval=a[2:];
			else: optval=a[2];
			if cur_scope[0]==None:
				obj["options"][a[1]]=optval;
			else: cur_scope[1]["options"][a[1]]=optval;
			continue;
		if cur_scope[0]==None: #global scope
			if cmd=="iface": #add interface
				iface={"name":a[1],"options":{}};
				obj["interfaces"].append(iface);
				cur_scope=("interface", iface);
			elif cmd=="config": #add config
				conf={"name":a[1],"options":{}};
				obj["configs"].append(conf);
				cur_scope=("config", conf);
		elif cmd=="end":
			cur_scope=(None,None);
	return obj;
def start():
	pass;
def main():
	if len(sys.argv)<2:
		print("to use ifsrv, put '#!/path/to/ifsrv' at the top of your config file and put the config file in /etc/init.d/ or whatever; don't forget to chmod it");
		return 0;
	if len(sys.argv)<3:
		print("usage: %s (start|stop|reload)"%sys.argv[1]);
		return 0;
	f=open(sys.argv[1],'rb');
	print(readconfig(f));
	return 0;

if __name__ == '__main__':
	main();

