
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table table1;
	private global::Gtk.Table table2;
	private global::Gtk.CheckButton c_expand;
	private global::Gtk.CheckButton c_param;
	private global::Gtk.CheckButton c_save;
	private global::Gtk.HBox hbox1;
	private global::Gtk.RadioButton r_dontfollow;
	private global::Gtk.RadioButton r_follownext;
	private global::Gtk.RadioButton r_followprev;
	private global::Gtk.CheckButton c_expand1;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.Label label4;
	private global::Gtk.Label label5;
	private global::Gtk.Entry t_atoken;
	private global::Gtk.Entry t_expand;
	private global::Gtk.Entry t_param;
	private global::Gtk.Entry t_path;
	private global::Gtk.Entry t_save;
	private global::Gtk.Entry t_saveto;
	private global::Gtk.Table table3;
	private global::Gtk.Button button1;
	private global::Gtk.Button button2;
	private global::Gtk.Label label10;
	private global::Gtk.Label label11;
	private global::Gtk.Label label3;
	private global::Gtk.Label label6;
	private global::Gtk.Label label8;
	private global::Gtk.Label label9;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("trolllollol");
		this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./trollface200.png"));
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
		this.table1.Name = "table1";
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.table2 = new global::Gtk.Table (((uint)(6)), ((uint)(4)), false);
		this.table2.Name = "table2";
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.c_expand = new global::Gtk.CheckButton ();
		this.c_expand.CanFocus = true;
		this.c_expand.Name = "c_expand";
		this.c_expand.Label = global::Mono.Unix.Catalog.GetString ("expand");
		this.c_expand.DrawIndicator = true;
		this.c_expand.UseUnderline = true;
		this.table2.Add (this.c_expand);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2 [this.c_expand]));
		w1.TopAttach = ((uint)(5));
		w1.BottomAttach = ((uint)(6));
		w1.XOptions = ((global::Gtk.AttachOptions)(0));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.c_param = new global::Gtk.CheckButton ();
		this.c_param.CanFocus = true;
		this.c_param.Name = "c_param";
		this.c_param.Label = global::Mono.Unix.Catalog.GetString ("extra params");
		this.c_param.DrawIndicator = true;
		this.c_param.UseUnderline = true;
		this.table2.Add (this.c_param);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.c_param]));
		w2.TopAttach = ((uint)(2));
		w2.BottomAttach = ((uint)(3));
		w2.XOptions = ((global::Gtk.AttachOptions)(0));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.c_save = new global::Gtk.CheckButton ();
		this.c_save.CanFocus = true;
		this.c_save.Name = "c_save";
		this.c_save.Label = global::Mono.Unix.Catalog.GetString ("save urls");
		this.c_save.DrawIndicator = true;
		this.c_save.UseUnderline = true;
		this.table2.Add (this.c_save);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.c_save]));
		w3.TopAttach = ((uint)(5));
		w3.BottomAttach = ((uint)(6));
		w3.LeftAttach = ((uint)(2));
		w3.RightAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(0));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.r_dontfollow = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("don't follow"));
		this.r_dontfollow.CanFocus = true;
		this.r_dontfollow.Name = "r_dontfollow";
		this.r_dontfollow.DrawIndicator = true;
		this.r_dontfollow.UseUnderline = true;
		this.r_dontfollow.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.hbox1.Add (this.r_dontfollow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.r_dontfollow]));
		w4.Position = 0;
		w4.Expand = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.r_follownext = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("follow 'next'"));
		this.r_follownext.CanFocus = true;
		this.r_follownext.Name = "r_follownext";
		this.r_follownext.DrawIndicator = true;
		this.r_follownext.UseUnderline = true;
		this.r_follownext.Group = this.r_dontfollow.Group;
		this.hbox1.Add (this.r_follownext);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.r_follownext]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.r_followprev = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("follow 'previous'"));
		this.r_followprev.CanFocus = true;
		this.r_followprev.Name = "r_followprev";
		this.r_followprev.DrawIndicator = true;
		this.r_followprev.UseUnderline = true;
		this.r_followprev.Group = this.r_dontfollow.Group;
		this.hbox1.Add (this.r_followprev);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.r_followprev]));
		w6.Position = 2;
		w6.Expand = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.c_expand1 = new global::Gtk.CheckButton ();
		this.c_expand1.TooltipMarkup = "whether to stop when an object fetched is found in the target directory";
		this.c_expand1.CanFocus = true;
		this.c_expand1.Name = "c_expand1";
		this.c_expand1.Label = global::Mono.Unix.Catalog.GetString ("stop on first existing object");
		this.c_expand1.DrawIndicator = true;
		this.c_expand1.UseUnderline = true;
		this.hbox1.Add (this.c_expand1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.c_expand1]));
		w7.Position = 3;
		w7.Expand = false;
		this.table2.Add (this.hbox1);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbox1]));
		w8.TopAttach = ((uint)(4));
		w8.BottomAttach = ((uint)(5));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("graph api path");
		this.table2.Add (this.label1);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.label1]));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("access token");
		this.table2.Add (this.label2);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.label2]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("paging");
		this.table2.Add (this.label4);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.label4]));
		w11.TopAttach = ((uint)(4));
		w11.BottomAttach = ((uint)(5));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("save to");
		this.table2.Add (this.label5);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.label5]));
		w12.TopAttach = ((uint)(3));
		w12.BottomAttach = ((uint)(4));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.t_atoken = new global::Gtk.Entry ();
		this.t_atoken.CanFocus = true;
		this.t_atoken.Name = "t_atoken";
		this.t_atoken.IsEditable = true;
		this.t_atoken.InvisibleChar = '•';
		this.table2.Add (this.t_atoken);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.t_atoken]));
		w13.TopAttach = ((uint)(1));
		w13.BottomAttach = ((uint)(2));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(4));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.t_expand = new global::Gtk.Entry ();
		this.t_expand.TooltipMarkup = "the fields that should be interpreted as ID's and followed; separated by a space";
		this.t_expand.CanFocus = true;
		this.t_expand.Name = "t_expand";
		this.t_expand.Text = global::Mono.Unix.Catalog.GetString ("object_id");
		this.t_expand.IsEditable = true;
		this.t_expand.InvisibleChar = '•';
		this.table2.Add (this.t_expand);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.t_expand]));
		w14.TopAttach = ((uint)(5));
		w14.BottomAttach = ((uint)(6));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(2));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.t_param = new global::Gtk.Entry ();
		this.t_param.CanFocus = true;
		this.t_param.Name = "t_param";
		this.t_param.Text = global::Mono.Unix.Catalog.GetString ("with=picture");
		this.t_param.IsEditable = true;
		this.t_param.InvisibleChar = '•';
		this.table2.Add (this.t_param);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2 [this.t_param]));
		w15.TopAttach = ((uint)(2));
		w15.BottomAttach = ((uint)(3));
		w15.LeftAttach = ((uint)(1));
		w15.RightAttach = ((uint)(4));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.t_path = new global::Gtk.Entry ();
		this.t_path.CanFocus = true;
		this.t_path.Name = "t_path";
		this.t_path.Text = global::Mono.Unix.Catalog.GetString ("/me/feed");
		this.t_path.IsEditable = true;
		this.t_path.InvisibleChar = '•';
		this.table2.Add (this.t_path);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2 [this.t_path]));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.t_save = new global::Gtk.Entry ();
		this.t_save.TooltipMarkup = "the fields that should be interpreted as urls and saved to disk directly without parsing; separated by a space";
		this.t_save.CanFocus = true;
		this.t_save.Name = "t_save";
		this.t_save.Text = global::Mono.Unix.Catalog.GetString ("source");
		this.t_save.IsEditable = true;
		this.t_save.InvisibleChar = '•';
		this.table2.Add (this.t_save);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2 [this.t_save]));
		w17.TopAttach = ((uint)(5));
		w17.BottomAttach = ((uint)(6));
		w17.LeftAttach = ((uint)(3));
		w17.RightAttach = ((uint)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.t_saveto = new global::Gtk.Entry ();
		this.t_saveto.CanFocus = true;
		this.t_saveto.Name = "t_saveto";
		this.t_saveto.Text = global::Mono.Unix.Catalog.GetString ("./");
		this.t_saveto.IsEditable = true;
		this.t_saveto.InvisibleChar = '•';
		this.table2.Add (this.t_saveto);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2 [this.t_saveto]));
		w18.TopAttach = ((uint)(3));
		w18.BottomAttach = ((uint)(4));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(4));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table1.Add (this.table2);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.table2]));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.table3 = new global::Gtk.Table (((uint)(1)), ((uint)(8)), false);
		this.table3.Name = "table3";
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		// Container child button1.Gtk.Container+ContainerChild
		global::Gtk.Alignment w20 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w21 = new global::Gtk.HBox ();
		w21.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w22 = new global::Gtk.Image ();
		w22.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-play", global::Gtk.IconSize.Menu);
		w21.Add (w22);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w24 = new global::Gtk.Label ();
		w24.LabelProp = global::Mono.Unix.Catalog.GetString ("start");
		w24.UseUnderline = true;
		w21.Add (w24);
		w20.Add (w21);
		this.button1.Add (w20);
		this.table3.Add (this.button1);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table3 [this.button1]));
		w28.XOptions = ((global::Gtk.AttachOptions)(0));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button2 = new global::Gtk.Button ();
		this.button2.Sensitive = false;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		// Container child button2.Gtk.Container+ContainerChild
		global::Gtk.Alignment w29 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w30 = new global::Gtk.HBox ();
		w30.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w31 = new global::Gtk.Image ();
		w31.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-stop", global::Gtk.IconSize.Menu);
		w30.Add (w31);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w33 = new global::Gtk.Label ();
		w33.LabelProp = global::Mono.Unix.Catalog.GetString ("stop");
		w33.UseUnderline = true;
		w30.Add (w33);
		w29.Add (w30);
		this.button2.Add (w29);
		this.table3.Add (this.button2);
		global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table3 [this.button2]));
		w37.LeftAttach = ((uint)(1));
		w37.RightAttach = ((uint)(2));
		w37.XOptions = ((global::Gtk.AttachOptions)(0));
		w37.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table3.Add (this.label10);
		global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table3 [this.label10]));
		w38.LeftAttach = ((uint)(6));
		w38.RightAttach = ((uint)(7));
		w38.XOptions = ((global::Gtk.AttachOptions)(4));
		w38.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.Xalign = 0F;
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("already exists");
		this.table3.Add (this.label11);
		global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table3 [this.label11]));
		w39.LeftAttach = ((uint)(7));
		w39.RightAttach = ((uint)(8));
		w39.XOptions = ((global::Gtk.AttachOptions)(4));
		w39.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table3.Add (this.label3);
		global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table3 [this.label3]));
		w40.LeftAttach = ((uint)(2));
		w40.RightAttach = ((uint)(3));
		w40.XOptions = ((global::Gtk.AttachOptions)(0));
		w40.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.Xalign = 0F;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("pages fetched containing");
		this.table3.Add (this.label6);
		global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table3 [this.label6]));
		w41.LeftAttach = ((uint)(3));
		w41.RightAttach = ((uint)(4));
		w41.XOptions = ((global::Gtk.AttachOptions)(0));
		w41.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table3.Add (this.label8);
		global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table3 [this.label8]));
		w42.LeftAttach = ((uint)(4));
		w42.RightAttach = ((uint)(5));
		w42.XOptions = ((global::Gtk.AttachOptions)(4));
		w42.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.Xalign = 0F;
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("objects");
		this.table3.Add (this.label9);
		global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table3 [this.label9]));
		w43.LeftAttach = ((uint)(5));
		w43.RightAttach = ((uint)(6));
		w43.XOptions = ((global::Gtk.AttachOptions)(4));
		w43.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table1.Add (this.table3);
		global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table1 [this.table3]));
		w44.TopAttach = ((uint)(1));
		w44.BottomAttach = ((uint)(2));
		w44.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add (this.table1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 670;
		this.DefaultHeight = 237;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
	}
}
