gen_index: gen_index.C
	g++ gen_index.C -o gen_index --std=c++0x -L../lib -I../include -g3 -lcpoll -ljsoncpp -Wno-pmf-conversions -pthread
gen_dirindex: gen_dirindex.C
	g++ gen_dirindex.C -o gen_dirindex --std=c++0x -L../lib -I../include -g3 -lcpoll -Wno-pmf-conversions -pthread
