/*
 * cplib_func.H
 *
 *  Created on: May 22, 2012
 *      Author: s-wang_cary
 */

#ifndef CPLIB_FUNC_H_
#define CPLIB_FUNC_H_
#include <functional>
#include "headers/cplib.hpp"
using namespace std;
namespace xaxaxa
{
	namespace functions
	{
		/*struct async_readline
		{
			function<void(const BufferRef&)> cb;
			function<Int(const BufferRef&)> read_func;
			Int br;

			void start();

		};*/
	}
}


#endif /* CPLIB_FUNC_H_ */
